# External dependencies managed by chezmoi
# Run `chezmoi apply` to install/update these

# Zsh plugins (managed separately, Oh My Zsh installed via bootstrap)
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/fast-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zdharma-continuum/fast-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-completions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-completions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
